Repository depromeet/ygtang-client, pull requests merged in 2022-05, with the labels that each got.

#88 공용 컴포넌트 - ImageContent
  .eslintrc.js
  src/components/common/ImageContent.tsx
  src/components/common/icons/CancelIcon.tsx
  src/components/common/icons/index.ts
  src/pages/add/image.tsx
Labels: design

#86 Check List 공용 컴포넌트 구현
  src/components/common/CheckList.tsx
  src/components/common/icons/ChevronIcon.tsx
  src/pages/test/index.tsx
Labels: feat

#87 공용 컴포넌트 - Text Field
  package.json
  src/components/common/PortalWrapper.tsx
  src/components/common/TextField/Input.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/TextField/index.ts
  src/pages/test/index.tsx
  yarn.lock
Labels: feat, design, env

#89 localhost https 개발 환경 설정
  httpsDevServer.js
  package.json
Labels: env

#90 공용컴포넌트 - LinkThumbnail 구현
  src/components/LinkThumbnail.tsx
  src/pages/test/index.tsx
  src/styles/utils/textEllipisCss.ts
Labels: feat

#93 ThumbnailTag, Tag 디자인 추가 및 변경 #92
  src/components/common/Tag.tsx
Labels: feat

#94 공용 컴포넌트 - MemoText
  package.json
  src/components/common/TextField/MemoText.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/TextField/index.ts
  src/components/common/TextField/styles.ts
  src/hooks/common/useInput.ts
  src/pages/test/index.tsx
  src/pages/test/input.tsx
  yarn.lock
Labels: feat

#95 공용 컴포넌트 - Search Bar
  src/components/common/TextField/Input.tsx
  src/components/common/TextField/SearchBar.tsx
  src/components/common/TextField/index.ts
  src/components/common/icons/SearchIcon.tsx
  src/pages/test/index.tsx
Labels: feat

#96 package.json httpsDevServer 이름 문제 해결
  package.json
Labels: fix

#97 CheckList 컴포넌트의 input id에 react18의useId 사용하기
  src/components/common/CheckList.tsx
  src/pages/test/index.tsx
Labels: refactor

#98 로그인 - 로그인 뷰 구현
  src/components/common/Button/CTAButton.tsx
  src/components/common/Button/GhostButton.tsx
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/Theme/Theme.ts
Labels: feat

#107 영감 추가 - 이미지 타입
  src/components/common/ImageContent.tsx
  src/components/common/TextField/MemoText.tsx
  src/pages/add/image.tsx
Labels: design

#110 Input이 textarea일 때 하단 resize 숨기기
  src/components/common/TextField/Input.tsx
Labels: fix, design

#111 홈 화면 - 썸네일 컴포넌트 개발
  .github/codecov.yml
  package.json
  src/components/common/Tag.tsx
  src/components/home/ContentHeader.tsx
  src/components/home/ContentThumbnail.tsx
  src/components/home/ContentView.tsx
  src/pages/index.tsx
  src/remotes/insipiration.d.ts
  src/remotes/member.d.ts
  src/remotes/tag.d.ts
  src/utils/.gitkeep
  src/utils/selectRandomColor/index.ts
  src/utils/selectRandomColor/selectRandomColor.ts
Labels: feat, design, env

#113 영감 추가 - 링크 타입
  src/components/LinkThumbnail.tsx
  src/components/add/LinkInput.tsx
  src/pages/add/link.tsx
  src/utils/validator.ts
Labels: feat, design

#118 chevronLeft가 필요 없는 경우 navigationBar 대신 목업 요소 사용
  src/pages/login/index.tsx
Labels: refactor

#115 영감 추가 | 편집 - 태그
  @types/tag.d.ts
  src/components/TagForm/AppliedTags.tsx
  src/components/TagForm/RegisteredTagList.tsx
  src/components/TagForm/index.tsx
  src/components/common/Tag.tsx
  src/pages/add/tag.tsx
  src/pages/edit/tag.tsx
  src/store/AppliedTags/appliedTagsStates.ts
  src/store/AppliedTags/index.ts
  src/store/AppliedTags/useAppliedTags.ts
Labels: feat

#126 Life cycle 공용 훅 개발 및 테스트 코드 작성
  .eslintrc.js
  package.json
  src/hooks/common/useDidMount/index.test.ts
  src/hooks/common/useDidMount/index.ts
  src/hooks/common/useDidMount/useDidMount.test.tsx
  src/hooks/common/useDidMount/useDidMount.ts
  src/hooks/common/useDidUpdate/index.test.ts
  src/hooks/common/useDidUpdate/index.ts
  src/hooks/common/useDidUpdate/useDidUpdate.test.tsx
  src/hooks/common/useDidUpdate/useDidUpdate.ts
  src/hooks/common/useToggle/index.test.ts
  src/hooks/common/useToggle/index.ts
  src/hooks/common/useToggle/useToggle.test.tsx
  src/hooks/common/useToggle/useToggle.ts
  yarn.lock
Labels: feat, test

#122 회원가입 - 뷰
  src/components/common/Button/FilledButton.tsx
  src/components/common/Dialog.tsx
  src/constants/motions.ts
  src/pages/_app.tsx
  src/pages/signup/email-verified.tsx
  src/pages/signup/index.tsx
  src/pages/signup/sent-email.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: feat, design

#116 홈 화면 - 추가 버튼 개발
  src/components/common/PortalWrapper.tsx
  src/components/common/icons/ImageIcon.tsx
  src/components/common/icons/LinkIcon.tsx
  src/components/common/icons/index.ts
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
  src/constants/motions.ts
  src/hooks/common/useInternalRouter.ts
  src/pages/index.tsx
  src/styles/GlobalStyle/reset.ts
Labels: feat, design

#131 공용 훅 - useUserAgent
  src/hooks/common/useUserAgent.ts
  src/pages/test/index.tsx
Labels: feat

#132 홈 화면 - 썸네일 - 링크 타입 개발
  src/components/home/ContentThumbnail.tsx
  src/pages/index.tsx
  src/remotes/insipiration.d.ts
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: feat, design

#133 공용 컴포넌트 - CTABottomButton
  src/components/common/Button/CTABottomButton.tsx
  src/hooks/common/useUserAgent.ts
  src/pages/test/index.tsx
Labels: feat, design

#140 홈 화면 - 네비게이션 바 + 태그 추가 개발 w/ 공용 훅
  src/components/TagForm/index.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/home/AppendButton.tsx
  src/components/home/HomeNavigationBar.tsx
  src/components/home/TagFormRouteAsModal.tsx
  src/hooks/common/useInternalRouter.ts
  src/hooks/common/usePreventScroll/index.ts
  src/hooks/common/usePreventScroll/usePreventScroll.ts
  src/hooks/common/useRouterQuery/index.ts
  src/hooks/common/useRouterQuery/useRouterQuery.ts
  src/pages/_app.tsx
  src/pages/add/tag.tsx
  src/pages/edit/tag.tsx
  src/pages/index.tsx
  src/pages/tag/index.tsx
  src/store/FilteredTags/filteredTagsStates.ts
  src/store/FilteredTags/index.ts
  src/store/FilteredTags/useFilteredTags.ts
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: feat, design

#119 로그인 - 유저 스토어 and api 연동
  .gitignore
  next.config.js
  package.json
  src/constants/common.ts
  src/hooks/api/reissue/useReissueMutation.ts
  src/hooks/common/useCookie.ts
  src/libs/api/client.ts
  src/libs/api/fetcher.ts
  src/libs/api/queryClient.ts
  src/pages/_app.tsx
  src/remotes/auth.d.ts
  src/store/User/UserProvider.tsx
  src/store/User/index.ts
  src/store/User/useUser.ts
  src/store/User/userStates.ts
  yarn.lock
Labels: feat, env, chore

#137 영감 추가 | 상세 - 태그 컨텐츠 추가
  @types/tag.d.ts
  src/components/common/Content/TagContent.tsx
  src/components/common/TextField/MemoText.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/styles.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/remotes/tag.d.ts
Labels: feat

#151 singup/email-verified CTABottomButton 적용 및 CTABottomButton 업데이트
  src/components/common/Button/CTABottomButton.tsx
  src/components/common/Button/index.tsx
  src/pages/signup/email-verified.tsx
Labels: feat, fix, design

#139 마이페이지 - 태그 관리
  src/components/common/icons/RemoveCircleIcon.tsx
  src/components/my/Menu.tsx
  src/components/my/tag/MyTagItem.tsx
  src/pages/my/tag/index.tsx
  src/remotes/tag.d.ts
Labels: feat

#158 마이페이지 - 테그관리 - 등록 모달 (BottomSheetModal)
  src/components/common/BottomSheetModal.tsx
  src/pages/my/tag/AddTagBottomSheet.tsx
  src/pages/my/tag/index.tsx
Labels: feat

#166 변경된 API 대응 및 reissue 인증 테스트
  src/constants/common.ts
  src/hooks/api/member/useMemberLoginMutation.ts
  src/hooks/api/reissue/useReissueMutation.ts
  src/libs/api/client.ts
  src/pages/login/index.tsx
  src/store/User/UserProvider.tsx
  src/store/User/useUser.ts
Labels: feat, chore

#157 Tag 비동기 관련 hook 개발
  next.config.js
  src/components/home/ContentThumbnail.tsx
  src/hooks/api/tag/useGetTagListWithInfinite.ts
  src/hooks/api/tag/useTagMutation.ts
  src/hooks/api/tag/useTagRefresh.ts
  src/libs/api/client.ts
  src/libs/api/queryClient.ts
  src/pages/_app.tsx
  src/pages/tag/index.tsx
  src/remotes/pagination.d.ts
Labels: feat

#174 Spinner, FixedSpinner, LoadingHandler 컴포넌트 개발
  src/components/common/LoadingHandler/LoadingHandler.tsx
  src/components/common/LoadingHandler/index.tsx
  src/components/common/Spinner/FixedSpinner.tsx
  src/components/common/Spinner/Spinner.tsx
  src/components/common/Spinner/index.tsx
  src/pages/tag/index.tsx
Labels: feat, design

#176 영감 추가 - 이미지 API 연결
  src/components/common/ImageContent.tsx
  src/components/home/AppendTooltip.tsx
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/libs/api/queryClient.ts
  src/pages/add/image.tsx
  src/store/UploadedImage/UploadedImgState.ts
  src/store/UploadedImage/index.ts
  src/store/UploadedImage/useUploadedImg.ts
Labels: feat

#181 레이아웃 - 모바일 url 바에 따른 100vh 자동 조절
  src/components/common/BottomSheetModal.tsx
  src/components/common/Dialog.tsx
  src/components/common/IllustDialog.tsx
  src/components/home/AppendButton.tsx
  src/components/home/TagFormRouteAsModal.tsx
  src/hooks/common/useWindowSize.ts
  src/pages/_app.tsx
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/pages/my/tag/index.tsx
  src/pages/signup/email-verified.tsx
Labels: design

#182 홈 화면 영감 비동기 작업 및 Empty 핸들링
  public/InspirationEmpty.png
  public/InspirationEmptyText.png
  src/components/common/Spinner/FixedSpinner.tsx
  src/components/home/EmptyImageSection.tsx
  src/components/home/HomeNavigationBar.tsx
  src/components/home/Thumbnail.tsx
  src/components/home/ThumbnailContent.tsx
  src/constants/assets.ts
  src/constants/motions.ts
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/pages/index.tsx
  src/pages/tag/index.tsx
  src/remotes/inspiration.d.ts
Labels: feat, design

#189 영감 추가 - 이미지 추가 기능 완성 및 업로드 에러 해결
  src/components/add/ImgUploader.tsx
  src/components/common/ImageContent.tsx
  src/components/common/TextField/MemoText.tsx
  src/components/home/AppendTooltip.tsx
  src/hooks/common/useImgUpload.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/pages/test/index.tsx
Labels: feat, fix

#185 Router Guard 적용 및 Reissue mutation 수정
  src/hooks/api/reissue/useReissueMutation.ts
  src/hooks/common/useDidUpdate/useDidUpdate.ts
  src/hooks/common/useRouterGuard.tsx
  src/libs/api/client.ts
  src/pages/_app.tsx
  src/store/User/UserProvider.tsx
Labels: feat, fix

#191 영감 추가 - 텍스트, 링크 API 연결
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: feat

#192 홈 화면 z-index, iOS input zoom in 수정
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/Spinner/FixedSpinner.tsx
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
  src/components/home/HomeNavigationBar.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: hotfix

#196 테그 - 추가 모달 버그 및 readOnly추가
  src/components/TagForm/index.tsx
  src/components/common/Content/TagContent.tsx
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/pages/index.tsx
  src/pages/tag/index.tsx
Labels: feat

#200 영감 인터페이스 중 TagResponses 대응
  src/components/home/Thumbnail.tsx
  src/pages/index.tsx
  src/remotes/inspiration.d.ts
Labels: hotfix

#201 영감 추가 - 테그 추가 API 적용 및 Tag React.memo 적용
  src/components/TagForm/AppliedTags.tsx
  src/components/TagForm/index.tsx
  src/components/common/Tag.tsx
  src/hooks/api/tag/useTagMutation.ts
Labels: feat, fix

#205 영감 추가 - 이미지 base64에서 blob 타입으로 변경 관리
  src/hooks/common/useImgUpload.ts
  src/pages/add/image.tsx
  src/store/UploadedImage/UploadedImgState.ts
  src/store/UploadedImage/useUploadedImg.ts
Labels: fix

#209 영감 추가 - 링크 타입 영감 검증 api 연결 추가
  src/components/LinkThumbnail.tsx
  src/components/add/LinkInput.tsx
  src/hooks/api/inspiration/useCheckLinkAvailable.ts
  src/pages/add/link.tsx
  src/pages/test/index.tsx
Labels: feat

#213 영감 추가 후 메인 리스트 리프레시
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/hooks/api/inspiration/useInspirationMutation.ts
Labels: feat

#212 영감 추가 - unmounted일 때, tags 초기화
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/store/AppliedTags/useAppliedTags.ts
Labels: fix

#219 로그인 폼 - 입력 안했을 때 체크 떠있는 문제
  src/pages/login/index.tsx
  src/pages/signup/email-verified.tsx
  src/pages/signup/index.tsx
Labels: fix

#221 영감 상세보기 메모 보기 기능 추가
  src/components/home/Thumbnail.tsx
  src/components/inspiration/ImageView.tsx
  src/components/inspiration/LinkView.tsx
  src/components/inspiration/TextView.tsx
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/pages/index.tsx
  src/store/Inspiration/InspirationDetailState.ts
  src/store/Inspiration/useInspirationDetail.ts
Labels: feat

#222 영감 상세 보기 submit 버튼 삭제
  src/components/inspiration/ImageView.tsx
  src/components/inspiration/LinkView.tsx
  src/components/inspiration/TextView.tsx
Labels: design

#223 영감 삭제 기능 추가
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/pages/content/[contentId].tsx
Labels: feat

#229 태그 필터 화면 완료 버튼 추가 및 useInternalRouter 추가 기능 개발
  src/hooks/common/useInternalRouter.ts
  src/pages/tag/index.tsx
Labels: feat, design

#230 홈 화면 Empty 이미지 렌더링 문제 해결
  src/components/common/LoadingHandler/LoadingHandler.tsx
  src/components/home/EmptyImageSection.tsx
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/pages/index.tsx
Labels: fix, refactor

#237 태그 필터, 영감 보기 스크롤 이슈 해결
  src/components/add/AddTagFormRouteAsModal.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/home/TagFormRouteAsModal.tsx
  src/components/inspiration/InspirationViewAsModal.tsx
  src/pages/content/[contentId].tsx
Labels: fix, design

#244 테스트 커버리지 디렉토리 수정
  jest.config.js
Labels: test, env, :zap:

#242 온보딩 route 개발, SnapCarousel과 Indicator 컴포넌트 개발
  public/onboard_images/onboard_1.png
  public/onboard_images/onboard_2.png
  public/onboard_images/onboard_3.png
  src/components/common/SnapCarousel/Indicator.test.tsx
  src/components/common/SnapCarousel/Indicator.tsx
  src/components/common/SnapCarousel/SnapCarousel.test.tsx
  src/components/common/SnapCarousel/SnapCarousel.tsx
  src/components/common/SnapCarousel/index.test.tsx
  src/components/common/SnapCarousel/index.tsx
  src/components/onboard/OnboardContent.tsx
  src/components/onboard/index.tsx
  src/constants/assets.ts
  src/constants/common.ts
  src/hooks/common/useInternalRouter.ts
  src/hooks/common/useRouterGuard.tsx
  src/pages/onboard/index.tsx
Labels: feat, design, test

#241 마이페이지 - UI 구현 (1차)
  public/UserProfile.png
  src/components/common/CheckList.tsx
  src/components/my/InformationMenu.tsx
  src/components/my/Menu.tsx
  src/components/my/Profile.tsx
  src/constants/assets.ts
  src/constants/common.ts
  src/hooks/common/useInternalRouter.ts
  src/pages/my/account/chage-password.tsx
  src/pages/my/account/index.tsx
  src/pages/my/index.tsx
Labels: feat, design

#245 ResponseInterface에서 data 구조 사용 안하도록 수정
  src/hooks/api/member/useMemberLoginMutation.ts
  src/hooks/api/reissue/useReissueMutation.ts
  src/remotes/auth.d.ts
Labels: refactor

#246 마이페이지 - 로그아웃
  src/components/my/Profile.tsx
  src/store/User/UserProvider.tsx
  src/store/User/useUser.ts
Labels: feat

#247 인증 토큰 만료 시 갱신 후 재요청
  src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
  src/hooks/common/useAuthorizationIntercept.ts
  src/libs/api/client.ts
  src/pages/test/user.tsx
  src/store/User/UserProvider.tsx
  src/store/User/useUser.ts
Labels: feat

#248 GA, Hotjar 적용 및 유틸 개발, 적용
  src/hooks/ga/useGaPageview.ts
  src/libs/ga/ga.test.ts
  src/libs/ga/ga.ts
  src/libs/ga/index.test.ts
  src/libs/ga/index.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: feat, test, env

#251 wildcard export를 named export로 수정
  src/components/common/SnapCarousel/index.test.tsx
  src/components/common/SnapCarousel/index.tsx
  src/components/onboard/index.tsx
  src/libs/ga/index.test.ts
  src/libs/ga/index.ts
  src/styles/utils/index.ts
Labels: refactor, test, :zap:

#252 favicon 및 app icon 추가
  public/favicon.ico
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/manifest.json
  src/pages/_document.tsx
Labels: design

#256 믹스패널 부착 및 이벤트 기록 유틸 개발
  package.json
  src/pages/_app.tsx
  src/utils/analytics/event.ts
  src/utils/analytics/index.ts
  yarn.lock
Labels: feat

#257 Sentry Init, Errorboundary 개발 및 적용
  src/components/common/ErrorBoundary/ErrorBoundary.tsx
  src/components/common/ErrorBoundary/index.tsx
  src/pages/_app.tsx
Labels: feat

#258 영감 id 조회 api 연결 및 영감 삭제 다이얼로그 생성
  public/manifest.json
  src/components/common/IllustDialog.tsx
  src/components/home/Thumbnail.tsx
  src/components/inspiration/ImageView.tsx
  src/components/inspiration/InspirationViewAsModal.tsx
  src/components/inspiration/LinkView.tsx
  src/components/inspiration/TextView.tsx
  src/hooks/api/inspiration/useInspirationById.ts
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/pages/_document.tsx
  src/pages/content/[contentId].tsx
  src/pages/content/[inspirationId].tsx
  src/pages/my/index.tsx
  src/remotes/inspiration.d.ts
  src/store/Inspiration/InspirationDetailState.ts
  src/store/Inspiration/index.ts
  src/store/Inspiration/useInspirationDetail.ts
Labels: feat, refactor

#264 영감 수정 기능 추가
  src/components/add/LinkInput.tsx
  src/components/common/Content/TagContent.tsx
  src/components/common/ImageContent.tsx
  src/components/common/TextField/Input.tsx
  src/components/common/TextField/MemoText.tsx
  src/components/common/TextField/TextField.tsx
  src/components/inspiration/ImageView.tsx
  src/components/inspiration/LinkView.tsx
  src/components/inspiration/TextView.tsx
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/common/useInternalRouter.ts
  src/pages/add/image.tsx
Labels: feat, fix, refactor

#266 태그 리스트 무한 스크롤 & 태그 관리 API 추가 (#238, #179)
  src/components/my/tag/MyTagItem.tsx
  src/pages/add/tag.tsx
  src/pages/my/tag/AddTagBottomSheet.tsx
  src/pages/my/tag/index.tsx
  src/pages/tag/index.tsx
Labels: feat

#271 design: iOS disabled input text color 흐려짐 방지
  src/components/common/TextField/Input.tsx
Labels: design, :zap:

#277 회원가입 이메일 엔드포인트 수정
  src/hooks/api/auth/useSignupSendEmailMutation.ts
Labels: feat

#280 next export build로 인한 dynamic routing 제거
  src/components/add/AddTagFormRouteAsModal.tsx
  src/components/home/TagFormRouteAsModal.tsx
  src/components/home/Thumbnail.tsx
  src/components/inspiration/InspirationViewAsModal.tsx
  src/constants/common.ts
  src/pages/content/index.tsx
Labels: fix

#263 마이페이지 - 유저 정보 API 연결 (#240)
  src/components/my/Profile.tsx
  src/hooks/api/member/useGetUserInformation.ts
  src/hooks/api/member/useUserInformationMutaion.ts
  src/hooks/common/useInternalRouter.ts
  src/pages/my/account/change-nickname.tsx
  src/pages/my/account/change-password.tsx
  src/pages/my/account/index.tsx
  src/remotes/member.d.ts
  src/store/UserInformation/index.ts
  src/store/UserInformation/useUserInformation.ts
  src/store/UserInformation/userInformationStates.ts
Labels: feat

#283 E2E 테스트 환경 및 CI 구성 w/ Cypress
  .eslintrc.js
  .github/workflows/CI.yml
  .gitignore
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/1_before_login/onboard.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: test, env

#285 영감 조회 시 스크롤 복구 로직 수정
  src/pages/content/index.tsx
Labels: fix, :zap:

#287 onboard route E2E 테스트 코드 작성
  .github/ISSUE_TEMPLATE/test.md
  cypress.json
  cypress/integration/1_before_login/onboard.ts
Labels: test

#290 마이페이지 - 비밀번호 변경
  src/hooks/api/member/useChangePassword.ts
  src/pages/my/account/change-password.tsx
  src/pages/my/password.tsx
Labels: feat

#293 영감 상세 보기 애니메이션 추가 및 링크 썸네일 새 창으로 열기 추가
  src/components/LinkThumbnail.tsx
  src/pages/content/index.tsx
Labels: design, :zap:

#294 영감 memo 수정 시 focus out 될 때 저장
  src/components/common/TextField/Input.tsx
  src/components/common/TextField/MemoText.tsx
  src/components/inspiration/ImageView.tsx
  src/components/inspiration/LinkView.tsx
  src/components/inspiration/TextView.tsx
Labels: feat

#297 이메일 인증 완료 체크 api 주소 변경
  src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
Labels: fix, :zap:

#302 회원가입 - 개인정보 정책 | 이용약관 노션 링크 연결
  src/components/common/CheckList.tsx
  src/pages/signup/email-verified.tsx
  src/pages/test/index.tsx
Labels: feat, :zap:

#299 회원가입 시 버튼 텍스트 수정 및 회원가입 로직 리팩터링
  src/hooks/api/auth/useSignupSendEmailMutation.ts
  src/hooks/api/sign-up/useCheckExistsSignupMutation.ts
  src/pages/signup/index.tsx
  src/pages/signup/sent-email.tsx
Labels: fix, refactor

#305 썸네일 크기 가변 문제 대응
  src/components/home/Thumbnail.tsx
Labels: fix

#311 썸네일 aspect ratio padding 대응
  cypress/integration/1_before_login/onboard.ts
  src/components/home/Thumbnail.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: fix, :zap:

#307 인증은 하였지만 가입하지 않은 이메일 핸들링, 이메일 발송 로직 리팩토링
  src/hooks/api/sign-up/useCheckExistsSignupMutation.ts
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/remotes/auth.d.ts
Labels: fix, refactor

#324 앱 메모리 해제시 로그인 유지를 위한 로컬 스토리지 적용
  src/components/common/UserProvider/UserProvider.tsx
  src/components/common/UserProvider/index.test.tsx
  src/components/common/UserProvider/index.tsx
  src/components/my/Profile.tsx
  src/constants/localStorage.ts
  src/hooks/common/useAuthorizationIntercept.ts
  src/hooks/common/useRouterGuard.tsx
  src/hooks/common/useUser/index.test.ts
  src/hooks/common/useUser/index.ts
  src/hooks/common/useUser/useUser.ts
  src/libs/api/client.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/store/User/index.ts
  src/store/User/userStates.ts
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: fix

#327 iOS tag delete 아이콘 색상 대응, /my/tag route 완료 버튼 동작 추가
  src/components/common/Tag/Tag.tsx
  src/pages/my/tag/index.tsx
Labels: fix, design, :zap:

#313 설정 - 정보 초기화 API | 계정 삭제 API 적용
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/api/member/useMemberSignOutMutaion.ts
  src/pages/my/account/index.tsx
  src/pages/my/index.tsx
  src/pages/signup/email-verified.tsx
Labels: feat
