Repository depromeet/ygtang-client, pull requests merged in 2022-10, with the labels that each got.

#489 추가 필터링 개발
  .github/workflows/CI.yml
  cypress.config.ts
  package.json
  src/components/common/CheckList/CheckList.tsx
  src/components/common/CheckList/index.tsx
  src/components/home/FilterBottomSheetModal/CalendarFilterSection.tsx
  src/components/home/FilterBottomSheetModal/FilterBottomSheetModal.tsx
  src/components/home/FilterBottomSheetModal/InspirationKindSection.tsx
  src/components/home/FilterBottomSheetModal/TagFilterSection.tsx
  src/components/home/FilterBottomSheetModal/index.tsx
  src/components/home/HomeNavigationBar.tsx
  src/hooks/api/inspiration/useGetAllInspirations.ts
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/hooks/api/inspiration/utils.ts
  src/pages/index.tsx
  src/remotes/inspiration.d.ts
  src/store/CalendarFilter/calendarFilter.ts
  src/store/CalendarFilter/index.ts
  src/store/CalendarFilter/useCalendarFilter.ts
  src/store/InspirationKindFilter/index.ts
  src/store/InspirationKindFilter/inpirationKindFilter.ts
  src/store/InspirationKindFilter/useInspirationKindFilter.ts
  yarn.lock
Labels: feat

#496 Alert 색상 추가 및 적용
  src/components/common/TextField/Input.tsx
  src/components/common/TextField/TextField.tsx
  src/pages/login/index.tsx
  src/pages/signup/email-verified.tsx
  src/pages/signup/index.tsx
  src/styles/Theme/Theme.ts
Labels: design

#499 온보드 이미지 및 텍스트 변경
  public/onboard_images/onboard_2.png
  src/pages/onboard/index.tsx
Labels: design, chore, :zap:

#501 actions-next-bundle-analyzer 적용
  .github/workflows/CI.yml
Labels: feat, :zap:

#504 iOS 환경 영감 종류 필터링 디자인 에러 수정
  src/components/home/FilterBottomSheetModal/InspirationKindSection.tsx
Labels: fix, design, :zap:

#505 영감 조회시 생성 (업데이트) 시간 적용
  src/components/inspiration/ImageView.tsx
  src/components/inspiration/InspirationTime.tsx
  src/components/inspiration/LinkView.tsx
  src/components/inspiration/TextView.tsx
  src/components/inspiration/type.ts
Labels: feat, refactor

#506 비밀번호 찾기 이메일 발송 시 로딩 스피너 렌더링
  src/pages/password/index.tsx
Labels: feat, :zap:

#508 @tanstack/react-query 대응
  package.json
  src/hooks/api/auth/useCheckEmailVerifiedStatusMutation.ts
  src/hooks/api/auth/useCheckPasswordResetEmailVerifiedMutation.ts
  src/hooks/api/auth/useSendPasswordResetEmailMutation.ts
  src/hooks/api/auth/useSignupSendEmailMutation.ts
  src/hooks/api/inspiration/useCheckLinkAvailable.ts
  src/hooks/api/inspiration/useGetAllInspirations.ts
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/hooks/api/inspiration/useInspirationById.ts
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/api/member/useChangePassword.ts
  src/hooks/api/member/useGetUserInformation.ts
  src/hooks/api/member/useMemberLoginMutation.ts
  src/hooks/api/member/useMemberSignOutMutaion.ts
  src/hooks/api/member/useSendResetPasswordMutation.ts
  src/hooks/api/member/useUserInformationMutaion.ts
  src/hooks/api/reissue/useReissueMutation.ts
  src/hooks/api/sign-up/useCheckExistsNicknameMutation.ts
  src/hooks/api/sign-up/usePatchExtraInformation.ts
  src/hooks/api/sign-up/useSignupMutation.ts
  src/hooks/api/tag/useGetTagListWithInfinite.ts
  src/hooks/api/tag/useTagMutation.ts
  src/hooks/api/tag/useTagRefresh.ts
  src/hooks/common/useUser/useUser.ts
  src/libs/api/queryClient.ts
  src/pages/_app.tsx
  yarn.lock
Labels: refactor

#509 husky 적용
  .eslintrc.js
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.json
  commitlint.config.js
  package.json
  yarn.lock
Labels: feat

#510 url surfix의 인식 범위를 2~9으로 늘림
  src/utils/validator.ts
Labels: fix, :zap:
