Repository depromeet/ygtang-client, pull requests merged in 2022-08, with the labels that each got.

#474 이미지 저장 개발, AppMessage 관련 인터페이스 수정, IconButton 인터페이스 수정
  package.json
  src/components/common/BottomSheetModal.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Dialog.tsx
  src/components/common/IllustDialog.tsx
  src/components/common/ImageContent.tsx
  src/components/common/icons/DownloadIcon.tsx
  src/components/common/icons/index.ts
  src/components/common/styles.ts
  src/components/home/AppendButton.tsx
  src/components/home/ThumbnailContent.tsx
  src/components/inspiration/ImageView.tsx
  src/constants/motions.ts
  src/hooks/bridge/useAppMessage/AppMessageListener.tsx
  src/hooks/bridge/useAppMessage/useAppMessage.ts
  src/hooks/common/useUserAgent/useUserAgent.ts
  src/pages/add/share.tsx
  src/utils/common/imageDownload.ts
  yarn.lock
Labels: feat, refactor, design

#480 전체보기 이미지 z-index 값 수정
  src/components/common/ImageContent.tsx
Labels: fix, :zap:

#481 전체보기 이미지 transform-origin 속성 설정
  src/components/common/ImageContent.tsx
Labels: fix, :zap:

#482 전체보기 이미지 layout 트랜지션 삭제
  src/components/common/ImageContent.tsx
Labels: fix, :zap:

#485 개발 API 도입
  src/libs/api/client.ts
Labels: chore, :zap:

#488 readme owner에 해성님 추가
  README.md
Labels: docs, :zap:
