Repository depromeet/ygtang-client, pull requests merged in 2022-06, with the labels that each got.

#329 로그인, 로그아웃 시 react query 캐시 clear
  src/hooks/common/useUser/useUser.ts
Labels: fix, :zap:

#330 텍스트 필드에 그림자 생기는 현상
  src/components/common/TextField/Input.tsx
Labels: fix, :zap:

#338 비밀번호 변경 - 인증 조건에 맞는데도 불구하고 처리 안되는 문제 수정
  src/pages/my/account/change-password.tsx
Labels: fix, :zap:

#335 로그인 / 회원가입 - 비밀번호 찾기
  public/WrongAccess.svg
  src/hooks/api/member/useSendResetPasswordMutation.ts
  src/pages/password/index.tsx
  src/pages/password/sent-email.tsx
  src/pages/password/verified.tsx
Labels: feat, fix

#341 Button 컴포넌트 테스트 작성
  src/components/common/Button/Button.test.tsx
  src/components/common/Button/CTABottomButton.test.tsx
  src/components/common/Button/CTAButton.test.tsx
  src/components/common/Button/FilledButton.test.tsx
  src/components/common/Button/GhostButton.test.tsx
  src/components/common/Button/index.test.tsx
Labels: test

#342 useUserAgent 테스트 작성
  cypress/integration/1_before_login/onboard.ts
  src/hooks/common/useUserAgent/index.test.ts
  src/hooks/common/useUserAgent/index.ts
  src/hooks/common/useUserAgent/useUserAgent.test.ts
  src/hooks/common/useUserAgent/useUserAgent.ts
Labels: refactor, test

#340 닉네임 변경 조건 추가 및 리팩터링
  src/pages/my/account/change-nickname.tsx
  src/pages/my/account/index.tsx
  src/pages/my/index.tsx
Labels: fix, refactor

#337 이미지 영감 생성 중 X 버튼 오류 대응
  src/components/add/ImgUploader.test.tsx
  src/components/add/ImgUploader.tsx
  src/components/common/ImageContent.tsx
  src/components/home/AppendTooltip.tsx
  src/hooks/common/useImgUpload.ts
  src/pages/add/image.tsx
Labels: fix, test

#347 회원가입 - 뒤로 가기 버튼 동작하지 않음
  src/components/common/CheckList.tsx
Labels: fix

#346 태그관리 - 태그 삭제 모달 구현
  src/components/my/tag/MyTagItem.tsx
Labels: fix

#343 영감 추가 - 링크 타입 (패이스북 | 인스타그램 대응)
  src/components/add/LinkInput.tsx
  src/components/home/ThumbnailContent.tsx
  src/components/inspiration/LinkView.tsx
  src/hooks/api/inspiration/useIgnoreOpenGraph.ts
Labels: fix

#344 영감 추가|편집 - 영감 태깅 플로우 변경 대응 & 태그 폼의 padding 값을 재설정
  src/components/common/TagForm/RegisteredTagList.tsx
  src/components/common/TagForm/TagForm.tsx
  src/components/common/TextField/SearchBar.tsx
  src/pages/add/tag.tsx
  src/pages/edit/tag.tsx
Labels: fix

#354 layout 모듈화 및 webview safe-area 적용
  src/components/add/AddTagFormRouteAsModal.tsx
  src/components/common/PortalWrapper.tsx
  src/components/edit/EditTagFormRouteAsModal.tsx
  src/components/home/TagFormRouteAsModal.tsx
  src/components/inspiration/InspirationViewAsModal.tsx
  src/pages/_app.tsx
  src/pages/_layout.tsx
Labels: fix, design

#351 로그인 페이지 비밀번호 찾기 링크 연결
  src/pages/login/index.tsx
Labels: feat, :zap:

#358 100vh 적용 오류 해결
  src/pages/_layout.tsx
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/styles/utils/viewHeight/viewHeight.ts
Labels: fix, design, :zap:

#357 닉네임 변경 로직 보수
  src/pages/my/account/change-nickname.tsx
  src/pages/signup/email-verified.tsx
Labels: fix

#361 fix: isLoadign으로 tag 추가 연속 클릭시, 중복 적용 방지
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/pages/edit/tag.tsx
Labels: fix

#362 _layout 삭제 Modal safe-area 적용 및 append tooltip 위치 수정
  src/components/add/AddTagFormRouteAsModal.tsx
  src/components/common/ModalWrapper.tsx
  src/components/common/PortalWrapper.tsx
  src/components/edit/EditTagFormRouteAsModal.tsx
  src/components/home/AppendTooltip.tsx
  src/components/home/TagFormRouteAsModal.tsx
  src/components/inspiration/InspirationViewAsModal.tsx
  src/pages/_app.tsx
  src/pages/_layout.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
Labels: fix, refactor, design

#364 리드미 작성
  README.md
  eslint/README.md
  mock-server/README.md
Labels: docs

#365 App Store 링크 추가
  README.md
Labels: docs

#369 홈화면 링크 썸네일이 표시되지 않는 문제
  src/components/home/ThumbnailContent.tsx
Labels: fix, hotfix

#370 플러스 버튼 플로팅 위치 수정
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
Labels: design, :zap:

#374 업로드 가능 이미지 포맷 heic 제거
  src/components/add/ImgUploader.tsx
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: fix

#380 홈 화면 링크 섬네일 계속 안보이는 문제
  src/components/home/ThumbnailContent.tsx
Labels: fix

#377 태그 추가 시 태그 리스트 반영, 영감에 태그 부착 시 영감 리스트 반영
  src/components/common/TagForm/TagForm.tsx
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/api/tag/useTagMutation.ts
  src/hooks/api/tag/useTagRefresh.ts
Labels: fix

#383 링크 섬네일에서 og 데이터가 없는 경우 멈춰버리는 현상
  src/components/home/ThumbnailContent.tsx
Labels: hotfix

#385 링크 영감 개별 조회에서 이미지 에러 대응
  src/components/add/LinkInput.tsx
  src/components/add/LinkThumbnail.tsx
  src/components/home/ThumbnailContent.tsx
  src/hooks/common/useOpenGraphImage/index.test.ts
  src/hooks/common/useOpenGraphImage/index.ts
  src/hooks/common/useOpenGraphImage/useOpenGraphImage.test.ts
  src/hooks/common/useOpenGraphImage/useOpenGraphImage.ts
  src/pages/add/link.tsx
  src/pages/test/index.tsx
Labels: fix, refactor, test

#386 리드미 codecov 뱃지 링크 업데이트
  README.md
Labels: docs, :zap:

#372 README 링크 수정
  README.md
Labels: docs, :zap:

#388 링크 썸네일 간혈적으로 보이지 않는 문제, OpenGraphResponse 적용
  src/components/add/LinkInput.tsx
  src/components/add/LinkThumbnail.tsx
  src/components/home/Thumbnail.tsx
  src/components/home/ThumbnailContent.tsx
  src/components/inspiration/LinkView.tsx
  src/hooks/api/inspiration/useCheckLinkAvailable.ts
  src/hooks/api/inspiration/useIgnoreOpenGraph.ts
  src/hooks/common/useOpenGraphImage/useOpenGraphImage.ts
  src/pages/add/link.tsx
  src/pages/test/dialog.tsx
  src/pages/test/index.tsx
  src/pages/test/input.tsx
  src/pages/test/user.tsx
Labels: fix, refactor

#390 link http 프로토콜 부착 로직 추가
  src/hooks/api/inspiration/useCheckLinkAvailable.ts
Labels: feat, :zap:

#392 영감 추가에서 오류 발생 시 버튼이 다시 active되지 않는 문제
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: fix

#393 영감 추가 오류 시 토스트 메시지 띄움
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: feat

#397 login route E2E 테스트 코드 작성
  .github/workflows/CI.yml
  .gitignore
  cypress/integration/1_before_login/onboard.spec.ts
  cypress/integration/3_login/login_success.spec.ts
  cypress/integration/3_login/not_validate_input.spec.ts
  cypress/integration/3_login/route_buttons.spec.ts
Labels: test

#396 회원가입 이메일 발송 로직 로딩 핸들링
  src/components/common/Spinner/FixedSpinner.tsx
  src/pages/signup/index.tsx
Labels: feat, fix

#405 로그아웃 다이얼로그 추가
  src/components/my/Profile.tsx
Labels: feat

#404 링크 적합성 평가 API 적용 대응
  src/components/add/LinkInput.tsx
  src/components/home/ThumbnailContent.tsx
  src/components/inspiration/LinkView.tsx
  src/hooks/api/inspiration/useIgnoreOpenGraph.ts
Labels: fix

#407 image content max height 제한 제거 및 min height 수정
  src/components/common/ImageContent.tsx
Labels: design, :zap:

#409 링크 확인 로직 변경 + 로딩 핸들링
  src/components/add/LinkInput.tsx
  src/hooks/api/inspiration/useCheckLinkAvailable.ts
Labels: fix, refactor

#411 회원가입 후 로그인되도록 개발 및 성공, 실패 로직 위임
  src/hooks/api/sign-up/useSignupMutation.ts
  src/pages/signup/email-verified.tsx
Labels: feat, refactor

#414 fix: image content min-height 100px로 수정
  src/components/common/ImageContent.tsx
Labels: fix, design, :zap:

#416 영감 조회시 로딩 핸들링 수정
  src/components/common/Spinner/FixedSpinner.tsx
  src/pages/content/index.tsx
Labels: fix, design

#418 영감 생성시 로딩 처리
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: feat, refactor

#421 토스트 메세지 문구 수정
  src/components/add/LinkInput.tsx
  src/components/common/UserProvider/UserProvider.tsx
  src/components/my/tag/MyTagItem.tsx
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/api/member/useMemberSignOutMutaion.ts
  src/hooks/api/member/useUserInformationMutaion.ts
  src/hooks/api/sign-up/useSignupMutation.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/pages/edit/tag.tsx
  src/pages/login/index.tsx
  src/pages/my/tag/AddTagBottomSheet.tsx
  src/pages/password/index.tsx
  src/pages/password/verified.tsx
  src/pages/signup/email-verified.tsx
  src/pages/signup/index.tsx
  src/pages/signup/sent-email.tsx
  src/store/AppliedTags/useAppliedTags.ts
Labels: fix, :zap:

#428 input placeholder 일반 폰트색과 동일하게 보이는 이슈 해결
  src/components/common/TextField/Input.tsx
Labels: fix

#430 DropdownMenu 컴포넌트 개발
  jest.setup.js
  package.json
  src/components/common/DropdownMenu/DropdownMenu.test.tsx
  src/components/common/DropdownMenu/DropdownMenu.tsx
  src/components/common/DropdownMenu/index.test.tsx
  src/components/common/DropdownMenu/index.tsx
  src/constants/common.ts
  src/hooks/common/useInternalRouter.ts
  yarn.lock
Labels: feat, test

#434 add/image에서 redirect를 pc 한정 적용하도록 변경
  src/components/add/ImgUploader.tsx
  src/components/common/ImageContent.tsx
  src/pages/add/image.tsx
Labels: feat, design

#432 회원가입 시 추가 정보 플로우 개발
  src/components/common/DropdownMenu/DropdownMenu.test.tsx
  src/components/common/DropdownMenu/DropdownMenu.tsx
  src/hooks/api/sign-up/usePatchExtraInformation.ts
  src/hooks/api/sign-up/useSignupMutation.ts
  src/hooks/common/useInternalRouter.ts
  src/libs/api/client.ts
  src/pages/signup/email-verified.tsx
  src/pages/signup/index.tsx
  src/pages/signup/information.tsx
  src/store/Signup/signupUserState.ts
  src/store/Signup/useSignupUser.ts
Labels: feat

#437 사용자 추가 정보 이벤트 부착
  src/pages/signup/information.tsx
Labels: feat

#439 add/image isDesktop 채크 오류 해결하기
  src/pages/add/image.tsx
Labels: fix

#423 영감 공유하기 - LINK | TEXT (머지 천천히 될예정입니다....)
  src/components/add/LinkInput.tsx
  src/hooks/common/useDataShareMessage.ts
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: feat

#435 safe area 웹 적용 원복
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
  src/pages/_app.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/utils/viewHeight/viewHeight.ts
Labels: fix

#441 영감 공유하기 - IMAGE
  src/hooks/common/useDataShareMessage.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
  src/utils/common/index.ts
Labels: feat

#442 safe area 웹 임시 적용
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
  src/pages/_app.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/utils/viewHeight/viewHeight.ts
Labels: fix, :zap:

#445 영감공유하기 - IOS 영감 공유를 위한 refresh token 전송
  src/hooks/common/useUser/useUser.ts
Labels: feat

#447 태그 관리 - 태그 등록 모달 완료 누르면 저장되도록 변경
  src/components/common/NavigationBar/NavigationBar.tsx
  src/pages/my/tag/AddTagBottomSheet.tsx
Labels: feat

#453 영감 조회 크기 변경
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
Labels: chore, :zap:

#454 _app 마운트 시 로고 출력
  src/pages/_app.tsx
Labels: chore

#457 공유하기 - 비로그인 접근할 경우, 로그인 이후, redirect 해주기
  src/constants/common.ts
  src/constants/sessionStorage.ts
  src/hooks/common/useDataShareMessage.ts
  src/hooks/common/useLoginRedirect.ts
  src/hooks/common/useRouterGuard.tsx
  src/pages/login/index.tsx
Labels: feat

#448 safe area 웹 적용 원복
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
  src/pages/_app.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/utils/viewHeight/viewHeight.ts
Labels: fix, :zap:

#455 input disabled된 input 글자색 에러 해결
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/TextField/Input.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/icons/ChevronIcon.tsx
  src/pages/add/text.tsx
Labels: fix, design

#461 영감 추가버튼 위치 조정
  src/components/home/AppendButton.tsx
  src/components/home/AppendTooltip.tsx
Labels: fix, design

#463 유니버셜 링크, 딥 링크를 위한 인증 파일 게시
  public/.well-known/apple-app-site-association
  public/.well-known/assetlinks.json
Labels: feat

#466 Share 페이지 나가면 웹뷰에 message를 전송
  src/constants/common.ts
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/common/useWebViewMessage.ts
Labels: feat
