Repository depromeet/ygtang-client, pull requests merged in 2022-04, with the labels that each got.

#2 개발 환경 설정
  .babelrc.js
  .eslintrc.js
  .github/ISSUE_TEMPLATE/design.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/env.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/hotfix.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.js
  next-env.d.ts
  next.config.js
  package.json
  public/favicon.ico
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/libs/.gitkeep
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/store/.gitkeep
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/GlobalStyle/index.tsx
  src/styles/Theme/Theme.ts
  src/styles/Theme/emotion.d.ts
  src/styles/Theme/index.ts
  src/utils/.gitkeep
  tsconfig.json
  yarn.lock
Labels: env

#4 Lint CI 설정
  .github/workflows/CI.yml
  public/vercel.svg
Labels: env

#24 절대 경로 설정 및 추가 패키지 설치
  .eslintrc.js
  package.json
  src/components/.gitkeep
  src/pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: env

#28 공용 컴포넌트 - 인터널 링크 개발
  .eslintrc.js
  .gitignore
  eslint/lib/index.js
  eslint/lib/rules/internal-router-passhref.js
  eslint/lib/utils/node-attributes.js
  eslint/package.json
  eslint/yarn.lock
  package.json
  src/components/common/InternalLink.tsx
  src/hooks/common/useInternalRouter.ts
  yarn.lock
Labels: feat

#35 영감 보기 그리드 디자인 설정
  src/components/common/Tag.tsx
  src/components/home/ContentHeader.tsx
  src/components/home/ContentThumbnail.tsx
  src/components/home/ContentView.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/GlobalStyle/reset.ts
  src/styles/Theme/Theme.ts
Labels: feat, design

#36 User 스토어 생성
  .gitignore
  src/store/User/index.ts
  src/store/User/useUser.ts
  src/store/User/userStates.ts
Labels: feat, env

#44 PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: env

#42 최대 크기 레이아웃 설정
  src/pages/_app.tsx
Labels: env

#45 Ajax client 및 fetcher 개발
  src/libs/.gitkeep
  src/libs/api/client.ts
  src/libs/api/fetcher.ts
Labels: feat

#49 Router Guard 만들기
  src/constants/common.ts
  src/hooks/common/useRouterGuard.tsx
Labels: feat

#53 Mock 서버 개발 및 api client 적용
  mock-server/.gitignore
  mock-server/package.json
  mock-server/src/db.json
  mock-server/src/routes.json
  mock-server/yarn.lock
  src/libs/api/client.ts
  tsconfig.json
Labels: env

#51 app to web 테스트용 웹 사이트 개발 - useAppMessage 훅 개발
  .editorconfig
  @types/global.d.ts
  src/hooks/bridge/useAppMessage/AppMessageListener.tsx
  src/hooks/bridge/useAppMessage/index.ts
  src/hooks/bridge/useAppMessage/useAppMessage.ts
  tsconfig.json
Labels: feat, env

#55 Framer motion 상수 설정
  src/constants/.gitkeep
  src/constants/motions.ts
Labels: env

#67 app to web 테스트용 웹 사이트 개발 - 테스트용 페이지 생성
  src/pages/add/share.tsx
Labels: feat

#69 코드리뷰어 자동 설정 추가
  .github/CODEOWNERS
Labels: env

#59 Pretendard 폰트 적용
  src/pages/_document.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/GlobalStyle/reset.ts
Labels: design

#56 모달 관련 컴포넌트 및 훅 개발
  src/components/.gitkeep
  src/components/common/PortalWrapper.tsx
  src/hooks/common/useToggle.ts
Labels: feat

#65 emotion color palette 설정
  src/components/home/ContentHeader.tsx
  src/components/home/ContentThumbnail.tsx
  src/styles/GlobalStyle/GlobalStyle.tsx
  src/styles/Theme/Theme.ts
Labels: design

#66 공용 컴포넌트 - Tag, ThumnailTag 구현
  src/components/common/Tag.tsx
  src/components/common/ThumbnailTag.tsx
  src/components/home/ContentThumbnail.tsx
Labels: feat

#70 공용 컴포넌트 - 아이콘
  src/components/common/Svg.tsx
  src/components/common/icons/CheckCircleIcon.tsx
  src/components/common/icons/CheckIcon.tsx
  src/components/common/icons/ChevronIcon.tsx
  src/components/common/icons/CloseIcon.tsx
  src/components/common/icons/DeleteIcon.tsx
  src/components/common/icons/EditIcon.tsx
  src/components/common/icons/FilterIcon.tsx
  src/components/common/icons/HomeIcon.tsx
  src/components/common/icons/PlusIcon.tsx
  src/components/common/icons/RemoveCircleIcon.tsx
  src/components/common/icons/SearchIcon.tsx
  src/components/common/icons/SettingsIcon.tsx
  src/components/common/icons/index.ts
Labels: feat, design

#78 Toast 메세지 관련 개발
  src/components/common/ToastSection.tsx
  src/components/home/ContentThumbnail.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/test/index.tsx
  src/store/Toast/index.ts
  src/store/Toast/toastStates.ts
  src/store/Toast/useToast.ts
  src/styles/Theme/Theme.ts
Labels: feat, design

#81 Unit, Integration 테스트 환경 설정
  .eslintrc.js
  .github/codecov.yml
  .github/workflows/CI.yml
  jest.config.js
  jest.setup.js
  package.json
  src/components/common/Button/Button.test.tsx
  tsconfig.json
  yarn.lock
Labels: test, env

#84 NavigationBar 컴포넌트 개발
  jest.config.js
  src/__test__/utils/customRender.tsx
  src/__test__/utils/index.ts
  src/components/common/NavigationBar/NavigationBar.test.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/NavigationBar/index.test.tsx
  src/components/common/NavigationBar/index.tsx
  src/pages/test/index.tsx
Labels: feat, test
