Repository depromeet/ygtang-client, pull requests merged in 2022-07, with the labels that each got.

#468 태그 추가, 삭제 시 토스트 메세지 수정
  src/hooks/api/inspiration/useInspirationMutation.ts
Labels: fix, :zap:

#467 태그 추가 - 상단 바 완료버튼 추가
  src/components/common/TagForm/TagForm.tsx
  src/pages/add/tag.tsx
  src/pages/edit/tag.tsx
Labels: feat

#469 refactor 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: docs, :zap:

#472 Cypress 버전 업데이트
  .github/workflows/CI.yml
  cypress.config.ts
  cypress.json
  cypress/e2e/1_before_login/onboard.spec.ts
  cypress/e2e/3_login/login_success.spec.ts
  cypress/e2e/3_login/not_validate_input.spec.ts
  cypress/e2e/3_login/route_buttons.spec.ts
  cypress/support/e2e.js
  package.json
  yarn.lock
Labels: test, env

#476 회원가입 CTA 버튼 위치 수정
  .github/workflows/CI.yml
  src/pages/signup/email-verified.tsx
  src/pages/signup/information.tsx
Labels: fix, design, :zap:
