Repository depromeet/ygtang-client, pull requests merged in 2023-02, with the labels that each got.

#518 fix: 태그 관리 - 태그등록 버튼 위치 변경
  src/pages/my/tag/index.tsx
Labels: design

#517 모바일 공유하기 이후, 자동 닫히기
  src/hooks/api/inspiration/useInspirationMutation.ts
  src/hooks/common/useDataShareMessage.ts
  src/pages/add/image.tsx
  src/pages/add/link.tsx
  src/pages/add/text.tsx
Labels: feat

#520 리드미 수정
  README.md
Labels: docs, :zap:

#519 글자 영감과 메모 스타일 변경
  src/components/common/TextField/MemoText.tsx
  src/components/inspiration/TextView.tsx
  src/pages/content/index.tsx
Labels: style

#522 Custom Exception 정의 및 사용, timeout 적용
  src/exceptions/ApiException.ts
  src/exceptions/CustomException.ts
  src/exceptions/messages.ts
  src/exceptions/type.ts
  src/libs/api/client.ts
Labels: feat
