Repository depromeet/ygtang-client, pull requests merged in 2023-04, with the labels that each got.

#556 feat: 회원가입 시 연령 선택 제거
  src/hooks/api/sign-up/usePatchExtraInformation.ts
  src/pages/index.tsx
  src/pages/signup/information.tsx
Labels: feat, fix

#557 v1.1.3
  package.json
  src/hooks/api/sign-up/usePatchExtraInformation.ts
  src/pages/index.tsx
  src/pages/signup/information.tsx
Labels: feat

#560 저장 시 포매팅 적용
  .vscode/settings.json
Labels: chore, :zap:

#559 loading handler 테스트
  src/components/common/LoadingHandler/LoadingHandler.test.tsx
  src/components/common/LoadingHandler/index.test.tsx
Labels: test

#564 페이지뷰 이벤트에 버전 기록
  src/hooks/analytics/useRecordPageview.ts
Labels: feat

#565 믹스패널 유저 identify 호출
  @types/global.d.ts
  src/components/common/UserProvider/UserProvider.tsx
  src/hooks/api/member/useGetUserInformation.ts
  src/hooks/common/useUser/useUser.ts
  src/libs/mixpanel/index.test.ts
  src/libs/mixpanel/index.ts
  src/libs/mixpanel/mixpanel.test.ts
  src/libs/mixpanel/mixpanel.ts
  src/pages/login/index.tsx
Labels: feat
