Repository depromeet/ygtang-client, pull requests merged in 2023-05, with the labels that each got.

#573 sitemap, robots 추가
  .pnp.cjs
  .yarn/cache/@corex-deepmerge-npm-4.0.43-390ed1175e-f0103bfcfb.zip
  .yarn/cache/@next-env-npm-13.4.1-f0b7da3756-4736c9c6f7.zip
  .yarn/cache/next-sitemap-npm-4.0.9-2198b8b52f-3c9fa402e2.zip
  next-sitemap.config.js
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  yarn.lock
Labels: feat

#572 리드미 수정
  README.md
Labels: docs, :zap:

#579 svg, img vertical-align 추가
  src/styles/GlobalStyle/reset.ts
Labels: style
