Repository depromeet/ygtang-client, pull requests merged in 2023-03, with the labels that each got.

#525 의존성 업데이트 및 연관 작업, Sentry 설정 수정
  cypress/e2e/1_before_login/onboard.spec.ts
  cypress/e2e/3_login/login_success.spec.ts
  cypress/e2e/3_login/not_validate_input.spec.ts
  cypress/e2e/3_login/route_buttons.spec.ts
  cypress/tsconfig.json
  jest.config.js
  jest.setup.js
  next.config.js
  package.json
  sentry.edge.config.js
  src/components/common/Button/Button.test.tsx
  src/components/common/Button/CTABottomButton.test.tsx
  src/components/common/Button/CTAButton.test.tsx
  src/components/common/Button/FilledButton.test.tsx
  src/components/common/Button/GhostButton.test.tsx
  src/components/common/Content/TagContent.tsx
  src/components/common/InternalLink.tsx
  src/components/common/LoadingHandler/LoadingHandler.tsx
  src/components/common/PortalWrapper.tsx
  src/components/common/SnapCarousel/SnapCarousel.test.tsx
  src/components/common/Tag/Tag.test.tsx
  src/components/common/TagForm/RegisteredTagList.test.tsx
  src/components/common/ToastSection.tsx
  src/components/home/FilterBottomSheetModal/TagFilterSection.tsx
  src/hooks/bridge/useAppMessage/useAppMessage.ts
  src/hooks/common/useDidMount/useDidMount.test.tsx
  src/hooks/common/useDidUpdate/useDidUpdate.test.tsx
  src/libs/api/client.ts
  src/libs/ga/ga.test.ts
  src/pages/signup/information.tsx
  src/styles/utils/textEllipsisCss/textEllipsisCss.test.ts
  src/types/global.d.ts
  tsconfig.json
  yarn.lock
Labels: build, env, chore

#534 필터링 이벤트 부착
  src/components/home/FilterBottomSheetModal/CalendarFilterSection.tsx
  src/components/home/FilterBottomSheetModal/FilterBottomSheetModal.tsx
  src/components/home/FilterBottomSheetModal/TagFilterSection.tsx
  src/components/home/HomeNavigationBar.tsx
  src/pages/tag/index.tsx
Labels: feat, :zap:

#532 ci 트리거 브랜치 변경
  .github/workflows/CI.yml
  .github/workflows/codeql.yml
Labels: :zap:

#538 무한 스크롤이 2번 실행되는 문제 해결
  package.json
  src/hooks/common/useIntersectionObserver/useIntersectionObserver.ts
Labels: fix

#540 이벤트 기록 시 버전 포함
  .eslintrc.js
  @types/environment.d.ts
  @types/global.d.ts
  next.config.js
  package.json
  src/pages/signup/index.tsx
  src/pages/signup/information.tsx
  src/pages/signup/sent-email.tsx
  src/utils/analytics/event.ts
  tsconfig.json
Labels: chore

#549 영감 삭제, 추가 시 로드 로직 변경
  src/hooks/api/inspiration/useGetInspirationListWIthInfinite.ts
  src/hooks/api/inspiration/useInspirationMutation.ts
Labels: feat, :zap:

#542 Cancel icon 디자인 변경
  src/components/common/ImageContent.tsx
  src/components/common/icons/CancelIcon.tsx
Labels: style

#548 영감리스트 다음페이지 로딩 스피너 추가 스캘래톤 버전
  src/components/common/Skeleton/Container.tsx
  src/components/common/Skeleton/Thumbnail.tsx
  src/components/common/Skeleton/index.tsx
  src/pages/index.tsx
  src/styles/Theme/Theme.ts
Labels: feat

#544 링크 영감 OG 이미지 호출 시 무한 로딩
  src/hooks/api/inspiration/useCheckLinkAvailable.ts
Labels: fix

#551 chore: package version to v1.1.1
  package.json
Labels: chore

#552 fix: 안드로이드 다음페이지 트리거 이슈
  src/pages/index.tsx
Labels: fix
